-- -----------------------------------------------------------------------------
-- This file is automatically generated by hdl-registers version 8.1.0.
-- Code generator VhdlSimulationReadWritePackageGenerator version 1.1.1.
-- Generated 2026-05-13 20:23 from file regs_counter.toml at Git commit 2feecffd6075 (local changes present).
-- Register hash 71076fb400da5d61dbc4d4b8e12bf513b5d3decf.
-- -----------------------------------------------------------------------------

library ieee;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;

library vunit_lib;
use vunit_lib.bus_master_pkg.bus_master_t;
use vunit_lib.bus_master_pkg.read_bus;
use vunit_lib.bus_master_pkg.write_bus;
use vunit_lib.com_types_pkg.network_t;

library register_file;
use register_file.register_file_pkg.register_t;
use register_file.register_file_pkg.register_width;
use register_file.register_operations_pkg.register_bus_master;

use work.counter_regs_pkg.all;
use work.counter_register_record_pkg.all;


package counter_register_read_write_pkg is

  -- ---------------------------------------------------------------------------
  -- Read the 'conf' register as a plain 'register_t'.
  procedure read_counter_conf(
    signal net : inout network_t;
    value : out register_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Read the 'conf' register as an 'integer'.
  procedure read_counter_conf(
    signal net : inout network_t;
    value : out integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Read the 'conf' register.
  procedure read_counter_conf(
    signal net : inout network_t;
    value : out counter_conf_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Read the 'condition' field in the 'conf' register.
  procedure read_counter_conf_condition(
    signal net : inout network_t;
    value : out counter_conf_condition_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Read the 'increment' field in the 'conf' register.
  procedure read_counter_conf_increment(
    signal net : inout network_t;
    value : out counter_conf_increment_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Write the 'conf' register as an 'integer'.
  procedure write_counter_conf(
    signal net : inout network_t;
    value : in integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Write the 'conf' register.
  procedure write_counter_conf(
    signal net : inout network_t;
    value : in counter_conf_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Write the 'condition' field in the 'conf' register.
  -- Will read-modify-write the register to set the field to the supplied 'value'.
  procedure write_counter_conf_condition(
    signal net : inout network_t;
    value : in counter_conf_condition_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Write the 'increment' field in the 'conf' register.
  -- Will read-modify-write the register to set the field to the supplied 'value'.
  procedure write_counter_conf_increment(
    signal net : inout network_t;
    value : in counter_conf_increment_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );
  -- ---------------------------------------------------------------------------

  -- ---------------------------------------------------------------------------
  -- Write the 'command' register as an 'integer'.
  procedure write_counter_command(
    signal net : inout network_t;
    value : in integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Write the 'command' register.
  procedure write_counter_command(
    signal net : inout network_t;
    value : in counter_command_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Write the 'start' field in the 'command' register.
  -- Will write the whole register, with the field set to the 
  -- supplied 'value' and everything else set to default.
  procedure write_counter_command_start(
    signal net : inout network_t;
    value : in std_ulogic;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Write the 'stop' field in the 'command' register.
  -- Will write the whole register, with the field set to the 
  -- supplied 'value' and everything else set to default.
  procedure write_counter_command_stop(
    signal net : inout network_t;
    value : in std_ulogic;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );
  -- ---------------------------------------------------------------------------

  -- ---------------------------------------------------------------------------
  -- Read the 'status' register as a plain 'register_t'.
  procedure read_counter_status(
    signal net : inout network_t;
    value : out register_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Read the 'status' register as an 'integer'.
  procedure read_counter_status(
    signal net : inout network_t;
    value : out integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Read the 'status' register.
  procedure read_counter_status(
    signal net : inout network_t;
    value : out counter_status_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Read the 'enabled' field in the 'status' register.
  procedure read_counter_status_enabled(
    signal net : inout network_t;
    value : out std_ulogic;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );

  -- Read the 'pulse_count' field in the 'status' register.
  procedure read_counter_status_pulse_count(
    signal net : inout network_t;
    value : out counter_status_pulse_count_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  );
  -- ---------------------------------------------------------------------------

end package;

package body counter_register_read_write_pkg is

  -- ---------------------------------------------------------------------------
  -- Read the 'conf' register as a plain 'register_t'.
  procedure read_counter_conf(
    signal net : inout network_t;
    value : out register_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    constant reg_index : counter_register_range := counter_conf;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);
    variable reg_value : register_t := (others => '0');
  begin
    read_bus(
      net => net,
      bus_handle => bus_handle,
      address => std_logic_vector(reg_address),
      data => reg_value
    );
    value := reg_value;
  end procedure;

  -- Read the 'conf' register as an 'integer'.
  procedure read_counter_conf(
    signal net : inout network_t;
    value : out integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    constant reg_index : counter_register_range := counter_conf;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);
    variable reg_value : register_t := (others => '0');
  begin
    read_bus(
      net => net,
      bus_handle => bus_handle,
      address => std_logic_vector(reg_address),
      data => reg_value
    );
    value := to_integer(unsigned(reg_value));
  end procedure;

  -- Read the 'conf' register.
  procedure read_counter_conf(
    signal net : inout network_t;
    value : out counter_conf_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    constant reg_index : counter_register_range := counter_conf;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);
    variable reg_value : register_t := (others => '0');
  begin
    read_bus(
      net => net,
      bus_handle => bus_handle,
      address => std_logic_vector(reg_address),
      data => reg_value
    );
    value := to_counter_conf(reg_value);
  end procedure;

  -- Read the 'condition' field in the 'conf' register.
  procedure read_counter_conf_condition(
    signal net : inout network_t;
    value : out counter_conf_condition_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    variable reg_value : counter_conf_t := counter_conf_init;
  begin
    read_counter_conf(
      net => net,
      value => reg_value,
      base_address => base_address,
      bus_handle => bus_handle
    );
    value := reg_value.condition;
  end procedure;

  -- Read the 'increment' field in the 'conf' register.
  procedure read_counter_conf_increment(
    signal net : inout network_t;
    value : out counter_conf_increment_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    variable reg_value : counter_conf_t := counter_conf_init;
  begin
    read_counter_conf(
      net => net,
      value => reg_value,
      base_address => base_address,
      bus_handle => bus_handle
    );
    value := reg_value.increment;
  end procedure;

  -- Write the 'conf' register as an 'integer'.
  procedure write_counter_conf(
    signal net : inout network_t;
    value : in integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    constant reg_index : counter_register_range := counter_conf;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);
    constant reg_value : register_t := std_ulogic_vector(to_unsigned(value, register_width));
  begin
    write_bus(
      net => net,
      bus_handle => bus_handle,
      address => std_logic_vector(reg_address),
      data => reg_value
    );
  end procedure;

  -- Write the 'conf' register.
  procedure write_counter_conf(
    signal net : inout network_t;
    value : in counter_conf_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    constant reg_index : counter_register_range := counter_conf;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);
    constant reg_value : register_t := to_slv(value);
  begin
    write_bus(
      net => net,
      bus_handle => bus_handle,
      address => std_logic_vector(reg_address),
      data => reg_value
    );
  end procedure;

  -- Write the 'condition' field in the 'conf' register.
  -- Will read-modify-write the register to set the field to the supplied 'value'.
  procedure write_counter_conf_condition(
    signal net : inout network_t;
    value : in counter_conf_condition_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    variable reg_value : counter_conf_t := counter_conf_init;
  begin
    read_counter_conf(
      net => net,
      value => reg_value,
      base_address => base_address,
      bus_handle => bus_handle
    );
    reg_value.condition := value;

    write_counter_conf(
      net => net,
      value => reg_value,
      base_address => base_address,
      bus_handle => bus_handle
    );
  end procedure;

  -- Write the 'increment' field in the 'conf' register.
  -- Will read-modify-write the register to set the field to the supplied 'value'.
  procedure write_counter_conf_increment(
    signal net : inout network_t;
    value : in counter_conf_increment_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    variable reg_value : counter_conf_t := counter_conf_init;
  begin
    read_counter_conf(
      net => net,
      value => reg_value,
      base_address => base_address,
      bus_handle => bus_handle
    );
    reg_value.increment := value;

    write_counter_conf(
      net => net,
      value => reg_value,
      base_address => base_address,
      bus_handle => bus_handle
    );
  end procedure;
  -- ---------------------------------------------------------------------------

  -- ---------------------------------------------------------------------------
  -- Write the 'command' register as an 'integer'.
  procedure write_counter_command(
    signal net : inout network_t;
    value : in integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    constant reg_index : counter_register_range := counter_command;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);
    constant reg_value : register_t := std_ulogic_vector(to_unsigned(value, register_width));
  begin
    write_bus(
      net => net,
      bus_handle => bus_handle,
      address => std_logic_vector(reg_address),
      data => reg_value
    );
  end procedure;

  -- Write the 'command' register.
  procedure write_counter_command(
    signal net : inout network_t;
    value : in counter_command_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    constant reg_index : counter_register_range := counter_command;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);
    constant reg_value : register_t := to_slv(value);
  begin
    write_bus(
      net => net,
      bus_handle => bus_handle,
      address => std_logic_vector(reg_address),
      data => reg_value
    );
  end procedure;

  -- Write the 'start' field in the 'command' register.
  -- Will write the whole register, with the field set to the 
  -- supplied 'value' and everything else set to default.
  procedure write_counter_command_start(
    signal net : inout network_t;
    value : in std_ulogic;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    variable reg_value : counter_command_t := counter_command_init;
  begin
    reg_value.start := value;

    write_counter_command(
      net => net,
      value => reg_value,
      base_address => base_address,
      bus_handle => bus_handle
    );
  end procedure;

  -- Write the 'stop' field in the 'command' register.
  -- Will write the whole register, with the field set to the 
  -- supplied 'value' and everything else set to default.
  procedure write_counter_command_stop(
    signal net : inout network_t;
    value : in std_ulogic;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    variable reg_value : counter_command_t := counter_command_init;
  begin
    reg_value.stop := value;

    write_counter_command(
      net => net,
      value => reg_value,
      base_address => base_address,
      bus_handle => bus_handle
    );
  end procedure;
  -- ---------------------------------------------------------------------------

  -- ---------------------------------------------------------------------------
  -- Read the 'status' register as a plain 'register_t'.
  procedure read_counter_status(
    signal net : inout network_t;
    value : out register_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    constant reg_index : counter_register_range := counter_status;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);
    variable reg_value : register_t := (others => '0');
  begin
    read_bus(
      net => net,
      bus_handle => bus_handle,
      address => std_logic_vector(reg_address),
      data => reg_value
    );
    value := reg_value;
  end procedure;

  -- Read the 'status' register as an 'integer'.
  procedure read_counter_status(
    signal net : inout network_t;
    value : out integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    constant reg_index : counter_register_range := counter_status;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);
    variable reg_value : register_t := (others => '0');
  begin
    read_bus(
      net => net,
      bus_handle => bus_handle,
      address => std_logic_vector(reg_address),
      data => reg_value
    );
    value := to_integer(unsigned(reg_value));
  end procedure;

  -- Read the 'status' register.
  procedure read_counter_status(
    signal net : inout network_t;
    value : out counter_status_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    constant reg_index : counter_register_range := counter_status;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);
    variable reg_value : register_t := (others => '0');
  begin
    read_bus(
      net => net,
      bus_handle => bus_handle,
      address => std_logic_vector(reg_address),
      data => reg_value
    );
    value := to_counter_status(reg_value);
  end procedure;

  -- Read the 'enabled' field in the 'status' register.
  procedure read_counter_status_enabled(
    signal net : inout network_t;
    value : out std_ulogic;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    variable reg_value : counter_status_t := counter_status_init;
  begin
    read_counter_status(
      net => net,
      value => reg_value,
      base_address => base_address,
      bus_handle => bus_handle
    );
    value := reg_value.enabled;
  end procedure;

  -- Read the 'pulse_count' field in the 'status' register.
  procedure read_counter_status_pulse_count(
    signal net : inout network_t;
    value : out counter_status_pulse_count_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master
  ) is
    variable reg_value : counter_status_t := counter_status_init;
  begin
    read_counter_status(
      net => net,
      value => reg_value,
      base_address => base_address,
      bus_handle => bus_handle
    );
    value := reg_value.pulse_count;
  end procedure;
  -- ---------------------------------------------------------------------------

end package body;
