-- -----------------------------------------------------------------------------
-- This file is automatically generated by hdl-registers version 8.1.0.
-- Code generator VhdlAxiLiteWrapperGenerator version 1.0.3.
-- Generated 2026-05-13 20:23 from file regs_counter.toml at Git commit 2feecffd6075 (local changes present).
-- Register hash 71076fb400da5d61dbc4d4b8e12bf513b5d3decf.
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- AXI-Lite register file for the 'counter' module registers.
-- Sets correct generics, and performs conversion to the easy-to-use register record types.
-- -----------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

-- This VHDL file is a required dependency:
-- https://github.com/hdl-modules/hdl-modules/blob/main/modules/axi_lite/src/axi_lite_pkg.vhd
-- See https://hdl-registers.com/rst/generator/generator_vhdl.html for dependency details.
library axi_lite;
use axi_lite.axi_lite_pkg.all;

-- This VHDL file is a required dependency:
-- https://github.com/hdl-modules/hdl-modules/blob/main/modules/register_file/src/axi_lite_register_file.vhd
-- See https://hdl-registers.com/rst/generator/generator_vhdl.html for dependency details.
library register_file;

use work.counter_regs_pkg.all;
use work.counter_register_record_pkg.all;


entity counter_register_file_axi_lite is
  port (
    clk : in std_ulogic;
    -- Active-high synchronous reset.
    -- The code in this entity uses initial values so an initial reset is NOT necessary.
    -- This port can safely be left unconnected and tied to zero.
    -- If asserted, it will reset the AXI-Lite handshaking state as well as all register values.
    reset : in std_ulogic := '0';
    --# {}
    --# Register control bus.
    axi_lite_m2s : in axi_lite_m2s_t;
    axi_lite_s2m : out axi_lite_s2m_t := axi_lite_s2m_init;
    --# {}
    -- Register values.
    regs_up : in counter_regs_up_t := counter_regs_up_init;
    regs_down : out counter_regs_down_t := counter_regs_down_init;
    --# {}
    -- Each bit is pulsed for one cycle when the corresponding register is read/written.
    reg_was_read : out counter_reg_was_read_t := counter_reg_was_read_init;
    reg_was_written : out counter_reg_was_written_t := counter_reg_was_written_init
  );
end entity;

architecture a of counter_register_file_axi_lite is

  signal regs_up_slv, regs_down_slv : counter_regs_t := counter_regs_init;

  signal reg_was_read_slv, reg_was_written_slv : counter_reg_was_accessed_t := (
    others => '0'
  );

begin

  ------------------------------------------------------------------------------
  -- Instantiate the generic register file implementation:
  -- https://github.com/hdl-modules/hdl-modules/blob/main/modules/register_file/src/axi_lite_register_file.vhd
  -- See https://hdl-registers.com/rst/generator/generator_vhdl.html for dependency details.
  axi_lite_register_file_inst : entity register_file.axi_lite_register_file
    generic map (
      registers => counter_register_map,
      default_values => counter_regs_init
    )
    port map(
      clk => clk,
      reset => reset,
      --
      axi_lite_m2s => axi_lite_m2s,
      axi_lite_s2m => axi_lite_s2m,
      --
      regs_up => regs_up_slv,
      regs_down => regs_down_slv,
      --
      reg_was_read => reg_was_read_slv,
      reg_was_written => reg_was_written_slv
    );


  ------------------------------------------------------------------------------
  -- Combinatorially convert the register record to a list of SLV values that can be handled
  -- by the generic register file implementation.
  assign_regs_up : process(regs_up)
  begin
    regs_up_slv <= to_slv(regs_up);
  end process;


  ------------------------------------------------------------------------------
  -- Combinatorially convert the list of SLV values from the generic register file into the record
  -- we want to use in our application.
  assign_regs_down : process(regs_down_slv)
  begin
    regs_down <= to_counter_regs_down(regs_down_slv);
  end process;


  ------------------------------------------------------------------------------
  -- Combinatorially convert status mask to a record where only the applicable registers are present.
  assign_reg_was_read : process(reg_was_read_slv)
  begin
    reg_was_read <= to_counter_reg_was_read(reg_was_read_slv);
  end process;


  ------------------------------------------------------------------------------
  -- Combinatorially convert status mask to a record where only the applicable registers are present.
  assign_reg_was_written : process(reg_was_written_slv)
  begin
    reg_was_written <= to_counter_reg_was_written(reg_was_written_slv);
  end process;

end architecture;
