-- -----------------------------------------------------------------------------
-- This file is automatically generated by hdl-registers version 8.1.0.
-- Code generator VhdlRecordPackageGenerator version 1.0.0.
-- Generated 2026-05-13 20:23 from file regs_counter.toml at Git commit 2feecffd6075 (local changes present).
-- Register hash 71076fb400da5d61dbc4d4b8e12bf513b5d3decf.
-- -----------------------------------------------------------------------------

library ieee;
use ieee.fixed_pkg.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library register_file;
use register_file.register_file_pkg.register_t;

use work.counter_regs_pkg.all;


package counter_register_record_pkg is

  -- -----------------------------------------------------------------------------
  -- Record with correctly-typed members for each field in each register.
  -- Fields in the 'conf' register as a record.
  type counter_conf_t is record
    condition : counter_conf_condition_t;
    increment : counter_conf_increment_t;
  end record;
  -- Default value for the 'conf' register as a record.
  constant counter_conf_init : counter_conf_t := (
    condition => counter_conf_condition_init,
    increment => counter_conf_increment_init
  );
  -- Convert a record of the 'conf' register to SLV.
  function to_slv(data : counter_conf_t) return register_t;
  -- Convert an SLV register value to the record for the 'conf' register.
  function to_counter_conf(data : register_t) return counter_conf_t;

  -- Fields in the 'command' register as a record.
  type counter_command_t is record
    start : std_ulogic;
    stop : std_ulogic;
  end record;
  -- Default value for the 'command' register as a record.
  constant counter_command_init : counter_command_t := (
    start => counter_command_start_init,
    stop => counter_command_stop_init
  );
  -- Convert a record of the 'command' register to SLV.
  function to_slv(data : counter_command_t) return register_t;
  -- Convert an SLV register value to the record for the 'command' register.
  function to_counter_command(data : register_t) return counter_command_t;

  -- Fields in the 'status' register as a record.
  type counter_status_t is record
    enabled : std_ulogic;
    pulse_count : counter_status_pulse_count_t;
  end record;
  -- Default value for the 'status' register as a record.
  constant counter_status_init : counter_status_t := (
    enabled => counter_status_enabled_init,
    pulse_count => counter_status_pulse_count_init
  );
  -- Convert a record of the 'status' register to SLV.
  function to_slv(data : counter_status_t) return register_t;
  -- Convert an SLV register value to the record for the 'status' register.
  function to_counter_status(data : register_t) return counter_status_t;

  -- -----------------------------------------------------------------------------
  -- Below is a record with correctly typed and ranged members for all registers, register arrays
  -- and fields that are in the 'up' direction.
  -- Record with everything in the 'up' direction.
  type counter_regs_up_t is record
    status : counter_status_t;
  end record;
  -- Default value of the above record.
  constant counter_regs_up_init : counter_regs_up_t := (
    status => counter_status_init
  );
  -- Convert record with everything in the 'up' direction to SLV register list.
  function to_slv(data : counter_regs_up_t) return counter_regs_t;

  -- -----------------------------------------------------------------------------
  -- Below is a record with correctly typed and ranged members for all registers, register arrays
  -- and fields that are in the 'down' direction.
  -- Record with everything in the 'down' direction.
  type counter_regs_down_t is record
    conf : counter_conf_t;
    command : counter_command_t;
  end record;
  -- Default value of the above record.
  constant counter_regs_down_init : counter_regs_down_t := (
    conf => counter_conf_init,
    command => counter_command_init
  );
  -- Convert SLV register list to record with everything in the 'down' direction.
  function to_counter_regs_down(data : counter_regs_t) return counter_regs_down_t;

  -- ---------------------------------------------------------------------------
  -- Below is a record with a status bit for each readable register in the register list.
  -- It can be used for the 'reg_was_read' port of a register file wrapper.
  -- Combined status mask record for all readable register.
  type counter_reg_was_read_t is record
    conf : std_ulogic;
    status : std_ulogic;
  end record;
  -- Default value for the above record.
  constant counter_reg_was_read_init : counter_reg_was_read_t := (
    others => '0'
  );
  -- Convert an SLV 'reg_was_read' from generic register file to the record above.
  function to_counter_reg_was_read(
    data : counter_reg_was_accessed_t
  ) return counter_reg_was_read_t;

  -- ---------------------------------------------------------------------------
  -- Below is a record with a status bit for each writeable register in the register list.
  -- It can be used for the 'reg_was_written' port of a register file wrapper.
  -- Combined status mask record for all writeable register.
  type counter_reg_was_written_t is record
    conf : std_ulogic;
    command : std_ulogic;
  end record;
  -- Default value for the above record.
  constant counter_reg_was_written_init : counter_reg_was_written_t := (
    others => '0'
  );
  -- Convert an SLV 'reg_was_written' from generic register file to the record above.
  function to_counter_reg_was_written(
    data : counter_reg_was_accessed_t
  ) return counter_reg_was_written_t;

end package;

package body counter_register_record_pkg is

  function to_slv(data : counter_conf_t) return register_t is
    variable result : register_t := (others => '-');
  begin
    result(counter_conf_condition) := to_slv(data.condition);
    result(counter_conf_increment) := to_counter_conf_increment_slv(data.increment);

    return result;
  end function;

  function to_counter_conf(data : register_t) return counter_conf_t is
    variable result : counter_conf_t := counter_conf_init;
  begin
    result.condition := to_counter_conf_condition(data);
    result.increment := to_counter_conf_increment(data);

    return result;
  end function;

  function to_slv(data : counter_command_t) return register_t is
    variable result : register_t := (others => '-');
  begin
    result(counter_command_start) := data.start;
    result(counter_command_stop) := data.stop;

    return result;
  end function;

  function to_counter_command(data : register_t) return counter_command_t is
    variable result : counter_command_t := counter_command_init;
  begin
    result.start := data(counter_command_start);
    result.stop := data(counter_command_stop);

    return result;
  end function;

  function to_slv(data : counter_status_t) return register_t is
    variable result : register_t := (others => '-');
  begin
    result(counter_status_enabled) := data.enabled;
    result(counter_status_pulse_count) := to_counter_status_pulse_count_slv(data.pulse_count);

    return result;
  end function;

  function to_counter_status(data : register_t) return counter_status_t is
    variable result : counter_status_t := counter_status_init;
  begin
    result.enabled := data(counter_status_enabled);
    result.pulse_count := to_counter_status_pulse_count(data);

    return result;
  end function;

  function to_slv(data : counter_regs_up_t) return counter_regs_t is
    variable result : counter_regs_t := counter_regs_init;
  begin
    result(counter_status) := to_slv(data.status);

    return result;
  end function;

  function to_counter_regs_down(data : counter_regs_t) return counter_regs_down_t is
    variable result : counter_regs_down_t := counter_regs_down_init;
  begin
    result.conf := to_counter_conf(data(counter_conf));
    result.command := to_counter_command(data(counter_command));

    return result;
  end function;

  function to_counter_reg_was_read(
    data : counter_reg_was_accessed_t
  ) return counter_reg_was_read_t is
    variable result : counter_reg_was_read_t := counter_reg_was_read_init;
  begin
    result.conf := data(counter_conf);
    result.status := data(counter_status);

    return result;
  end function;

  function to_counter_reg_was_written(
    data : counter_reg_was_accessed_t
  ) return counter_reg_was_written_t is
    variable result : counter_reg_was_written_t := counter_reg_was_written_init;
  begin
    result.conf := data(counter_conf);
    result.command := data(counter_command);

    return result;
  end function;

end package body;
