-- -----------------------------------------------------------------------------
-- This file is automatically generated by hdl-registers version 8.1.0.
-- Code generator VhdlRegisterPackageGenerator version 2.0.0.
-- Generated 2026-05-13 20:23 from file regs_counter.toml at Git commit 2feecffd6075 (local changes present).
-- Register hash 71076fb400da5d61dbc4d4b8e12bf513b5d3decf.
-- -----------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

library register_file;
use register_file.register_file_pkg.all;


package counter_regs_pkg is

  -- ---------------------------------------------------------------------------
  -- The valid range of register indexes.
  subtype counter_register_range is natural range 0 to 2;

  -- ---------------------------------------------------------------------------
  -- The number of bits needed to address all 3 registers on a register bus.
  -- Note that this figure includes the lowest two address bits that are assumed zero, since
  -- registers are 32-bit and unaligned accesses are not supported.
  constant counter_address_width : positive := 4;

  -- Register indexes, within the list of registers.
  constant counter_conf : natural := 0;
  constant counter_command : natural := 1;
  constant counter_status : natural := 2;

  -- Declare 'register_map' and 'regs_init' constants here but define them in
  -- the package body (deferred constants).
  -- So that functions have been elaborated when they are called.
  -- Needed for ModelSim compilation to pass.

  -- To be used as the 'registers' generic of 'axi_lite_register_file.vhd'.
  constant counter_register_map : register_definition_vec_t(counter_register_range);

  -- To be used for the 'regs_up' and 'regs_down' ports of 'axi_lite_register_file.vhd'.
  subtype counter_regs_t is register_vec_t(counter_register_range);
  -- To be used as the 'default_values' generic of 'axi_lite_register_file.vhd'.
  constant counter_regs_init : counter_regs_t;

  -- To be used for the 'reg_was_read' and 'reg_was_written' ports of 'axi_lite_register_file.vhd'.
  subtype counter_reg_was_accessed_t is std_ulogic_vector(counter_register_range);

  -- -----------------------------------------------------------------------------
  -- Fields in the 'conf' register.
  -- Range of the 'condition' field.
  subtype counter_conf_condition is natural range 1 downto 0;
  -- Width of the 'condition' field.
  constant counter_conf_condition_width : positive := 2;
  -- Type for the 'condition' field.
  type counter_conf_condition_t is (
    condition_clock_cycles,
    condition_clock_cycles_with_enable,
    condition_enable_edges
  );
  -- Default value of the 'condition' field.
  constant counter_conf_condition_init : counter_conf_condition_t := condition_clock_cycles;
  -- Type for the 'condition' field as an SLV.
  subtype counter_conf_condition_slv_t is std_ulogic_vector(1 downto 0);
  -- Cast a 'condition' field value to SLV.
  function to_slv(data : counter_conf_condition_t) return counter_conf_condition_slv_t;
  -- Get a 'condition' field value from a register value.
  function to_counter_conf_condition(data : register_t) return counter_conf_condition_t;

  -- Range of the 'increment' field.
  subtype counter_conf_increment is natural range 5 downto 2;
  -- Width of the 'increment' field.
  constant counter_conf_increment_width : positive := 4;
  -- Type for the 'increment' field.
  subtype counter_conf_increment_t is integer range 0 to 15;
  -- Default value of the 'increment' field.
  constant counter_conf_increment_init : counter_conf_increment_t := 0;
  -- Type for the 'increment' field as an SLV.
  subtype counter_conf_increment_slv_t is std_ulogic_vector(3 downto 0);
  -- Cast a 'increment' field value to SLV.
  function to_counter_conf_increment_slv(data : counter_conf_increment_t) return counter_conf_increment_slv_t;
  -- Get a 'increment' field value from a register value.
  function to_counter_conf_increment(data : register_t) return counter_conf_increment_t;

  -- -----------------------------------------------------------------------------
  -- Fields in the 'command' register.
  -- Range of the 'start' field.
  constant counter_command_start : natural := 0;
  -- Default value of the 'start' field.
  constant counter_command_start_init : std_ulogic := '0';

  -- Range of the 'stop' field.
  constant counter_command_stop : natural := 1;
  -- Default value of the 'stop' field.
  constant counter_command_stop_init : std_ulogic := '0';

  -- -----------------------------------------------------------------------------
  -- Fields in the 'status' register.
  -- Range of the 'enabled' field.
  constant counter_status_enabled : natural := 0;
  -- Default value of the 'enabled' field.
  constant counter_status_enabled_init : std_ulogic := '0';

  -- Range of the 'pulse_count' field.
  subtype counter_status_pulse_count is natural range 8 downto 1;
  -- Width of the 'pulse_count' field.
  constant counter_status_pulse_count_width : positive := 8;
  -- Type for the 'pulse_count' field.
  subtype counter_status_pulse_count_t is integer range 0 to 255;
  -- Default value of the 'pulse_count' field.
  constant counter_status_pulse_count_init : counter_status_pulse_count_t := 0;
  -- Type for the 'pulse_count' field as an SLV.
  subtype counter_status_pulse_count_slv_t is std_ulogic_vector(7 downto 0);
  -- Cast a 'pulse_count' field value to SLV.
  function to_counter_status_pulse_count_slv(data : counter_status_pulse_count_t) return counter_status_pulse_count_slv_t;
  -- Get a 'pulse_count' field value from a register value.
  function to_counter_status_pulse_count(data : register_t) return counter_status_pulse_count_t;

end package;

package body counter_regs_pkg is

  constant counter_register_map : register_definition_vec_t(counter_register_range) := (
    0 => (index => counter_conf, mode => r_w, utilized_width => 6),
    1 => (index => counter_command, mode => wpulse, utilized_width => 2),
    2 => (index => counter_status, mode => r, utilized_width => 9)
  );

  constant counter_regs_init : counter_regs_t := (
    0 => "00000000000000000000000000000000",
    1 => "00000000000000000000000000000000",
    2 => "00000000000000000000000000000000"
  );

  -- Cast a 'condition' field value to SLV.
  function to_slv(data : counter_conf_condition_t) return counter_conf_condition_slv_t is
    constant data_int : natural := counter_conf_condition_t'pos(data);
    constant result : counter_conf_condition_slv_t := std_ulogic_vector(
      to_unsigned(data_int, counter_conf_condition_width)
    );
  begin
    return result;
  end function;

  -- Get a 'condition' field value from a register value.
  function to_counter_conf_condition(data : register_t) return counter_conf_condition_t is
    constant field_slv : counter_conf_condition_slv_t := data(counter_conf_condition);
    constant field_int : natural := to_integer(unsigned(field_slv));
    constant result : counter_conf_condition_t := counter_conf_condition_t'val(field_int);
  begin
    return result;
  end function;

  -- Cast a 'increment' field value to SLV.
  function to_counter_conf_increment_slv(data : counter_conf_increment_t) return counter_conf_increment_slv_t is
    constant result : counter_conf_increment_slv_t := std_ulogic_vector(to_unsigned(data, counter_conf_increment_width));
  begin
    return result;
  end function;

  -- Get a 'increment' field value from a register value.
  function to_counter_conf_increment(data : register_t) return counter_conf_increment_t is
    constant result : integer := to_integer(unsigned(data(counter_conf_increment)));
  begin
    return result;
  end function;

  -- Cast a 'pulse_count' field value to SLV.
  function to_counter_status_pulse_count_slv(data : counter_status_pulse_count_t) return counter_status_pulse_count_slv_t is
    constant result : counter_status_pulse_count_slv_t := std_ulogic_vector(to_unsigned(data, counter_status_pulse_count_width));
  begin
    return result;
  end function;

  -- Get a 'pulse_count' field value from a register value.
  function to_counter_status_pulse_count(data : register_t) return counter_status_pulse_count_t is
    constant result : integer := to_integer(unsigned(data(counter_status_pulse_count)));
  begin
    return result;
  end function;

end package body;
