-- -----------------------------------------------------------------------------
-- This file is automatically generated by hdl-registers version 8.1.0.
-- Code generator VhdlSimulationCheckPackageGenerator version 1.2.1.
-- Generated 2026-05-13 20:23 from file regs_counter.toml at Git commit 2feecffd6075 (local changes present).
-- Register hash 71076fb400da5d61dbc4d4b8e12bf513b5d3decf.
-- -----------------------------------------------------------------------------

library ieee;
use ieee.fixed_pkg.all;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;

library vunit_lib;
use vunit_lib.bus_master_pkg.bus_master_t;
use vunit_lib.check_pkg.all;
use vunit_lib.checker_pkg.all;
use vunit_lib.com_types_pkg.network_t;
use vunit_lib.string_ops.hex_image;

library register_file;
use register_file.register_file_pkg.register_t;
use register_file.register_operations_pkg.register_bus_master;

use work.counter_register_read_write_pkg.all;
use work.counter_register_record_pkg.all;
use work.counter_regs_pkg.all;


package counter_register_check_pkg is

  -- ---------------------------------------------------------------------------
  -- Check that the current value of the 'conf' register
  -- equals the given 'expected' value as a plain SLV casted to integer.
  procedure check_counter_conf_equal(
    signal net : inout network_t;
    expected : in integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  );

  -- Check that the current value of the 'conf' register
  -- equals the given 'expected' value.
  procedure check_counter_conf_equal(
    signal net : inout network_t;
    expected : in counter_conf_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  );

  -- Check that the current value of the 'condition' field in the 'conf' register
  -- equals the given 'expected' value.
  procedure check_counter_conf_condition_equal(
    signal net : inout network_t;
    expected : in counter_conf_condition_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  );

  -- Check that the current value of the 'increment' field in the 'conf' register
  -- equals the given 'expected' value.
  procedure check_counter_conf_increment_equal(
    signal net : inout network_t;
    expected : in counter_conf_increment_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  );
  -- ---------------------------------------------------------------------------

  -- ---------------------------------------------------------------------------
  -- Check that the current value of the 'status' register
  -- equals the given 'expected' value as a plain SLV casted to integer.
  procedure check_counter_status_equal(
    signal net : inout network_t;
    expected : in integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  );

  -- Check that the current value of the 'status' register
  -- equals the given 'expected' value.
  procedure check_counter_status_equal(
    signal net : inout network_t;
    expected : in counter_status_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  );

  -- Check that the current value of the 'enabled' field in the 'status' register
  -- equals the given 'expected' value.
  procedure check_counter_status_enabled_equal(
    signal net : inout network_t;
    expected : in std_ulogic;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  );

  -- Check that the current value of the 'pulse_count' field in the 'status' register
  -- equals the given 'expected' value.
  procedure check_counter_status_pulse_count_equal(
    signal net : inout network_t;
    expected : in counter_status_pulse_count_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  );
  -- ---------------------------------------------------------------------------

end package;

package body counter_register_check_pkg is

  -- ---------------------------------------------------------------------------
  -- Check that the current value of the 'conf' register
  -- equals the given 'expected' value as a plain SLV casted to integer.
  procedure check_counter_conf_equal(
    signal net : inout network_t;
    expected : in integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  ) is
    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Checking the 'conf' register"
      & register_array_message
      & base_address_message
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;

    variable got : integer;
  begin
    read_counter_conf(
      net => net,
      value => got,
      base_address => base_address,
      bus_handle => bus_handle
    );

    check_equal(got=>got, expected=>expected, msg=>get_message);
  end procedure;

  -- Check that the current value of the 'conf' register
  -- equals the given 'expected' value.
  procedure check_counter_conf_equal(
    signal net : inout network_t;
    expected : in counter_conf_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  ) is
    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Checking the 'conf' register"
      & register_array_message
      & base_address_message
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;

    variable got : counter_conf_t;
  begin
    read_counter_conf(
      net => net,
      value => got,
      base_address => base_address,
      bus_handle => bus_handle
    );

    if got /= expected then
      failing_check(
        checker => default_checker,
        msg => p_std_msg(
          check_result => "Equality check failed",
          msg => get_message,
          ctx => (
            "Got " & to_string(to_slv(got)) & ". Expected " & to_string(to_slv(expected)) & "."
          )
        )
      );
    end if;
  end procedure;

  -- Check that the current value of the 'condition' field in the 'conf' register
  -- equals the given 'expected' value.
  procedure check_counter_conf_condition_equal(
    signal net : inout network_t;
    expected : in counter_conf_condition_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  ) is
    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Checking the 'condition' field in the 'conf' register"
      & register_array_message
      & base_address_message
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;

    variable got_reg : counter_conf_t := counter_conf_init;
    variable got : counter_conf_condition_t := counter_conf_condition_init;
  begin
    read_counter_conf(
      net => net,
      value => got_reg,
      base_address => base_address,
      bus_handle => bus_handle
    );
    got := got_reg.condition;

    if got /= expected then
      failing_check(
        checker => default_checker,
        msg => p_std_msg(
          check_result => "Equality check failed",
          msg => get_message,
          ctx => (
            "Got " & to_string(got) & "."
            & " Expected " & to_string(expected) & "."
          )
        )
      );
    end if;
  end procedure;

  -- Check that the current value of the 'increment' field in the 'conf' register
  -- equals the given 'expected' value.
  procedure check_counter_conf_increment_equal(
    signal net : inout network_t;
    expected : in counter_conf_increment_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  ) is
    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Checking the 'increment' field in the 'conf' register"
      & register_array_message
      & base_address_message
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;

    variable got_reg : counter_conf_t := counter_conf_init;
    variable got : counter_conf_increment_t := counter_conf_increment_init;
  begin
    read_counter_conf(
      net => net,
      value => got_reg,
      base_address => base_address,
      bus_handle => bus_handle
    );
    got := got_reg.increment;

    check_equal(got=>got, expected=>expected, msg=>get_message);
  end procedure;
  -- ---------------------------------------------------------------------------

  -- ---------------------------------------------------------------------------
  -- Check that the current value of the 'status' register
  -- equals the given 'expected' value as a plain SLV casted to integer.
  procedure check_counter_status_equal(
    signal net : inout network_t;
    expected : in integer;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  ) is
    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Checking the 'status' register"
      & register_array_message
      & base_address_message
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;

    variable got : integer;
  begin
    read_counter_status(
      net => net,
      value => got,
      base_address => base_address,
      bus_handle => bus_handle
    );

    check_equal(got=>got, expected=>expected, msg=>get_message);
  end procedure;

  -- Check that the current value of the 'status' register
  -- equals the given 'expected' value.
  procedure check_counter_status_equal(
    signal net : inout network_t;
    expected : in counter_status_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  ) is
    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Checking the 'status' register"
      & register_array_message
      & base_address_message
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;

    variable got : counter_status_t;
  begin
    read_counter_status(
      net => net,
      value => got,
      base_address => base_address,
      bus_handle => bus_handle
    );

    if got /= expected then
      failing_check(
        checker => default_checker,
        msg => p_std_msg(
          check_result => "Equality check failed",
          msg => get_message,
          ctx => (
            "Got " & to_string(to_slv(got)) & ". Expected " & to_string(to_slv(expected)) & "."
          )
        )
      );
    end if;
  end procedure;

  -- Check that the current value of the 'enabled' field in the 'status' register
  -- equals the given 'expected' value.
  procedure check_counter_status_enabled_equal(
    signal net : inout network_t;
    expected : in std_ulogic;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  ) is
    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Checking the 'enabled' field in the 'status' register"
      & register_array_message
      & base_address_message
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;

    variable got_reg : counter_status_t := counter_status_init;
    variable got : std_ulogic := counter_status_enabled_init;
  begin
    read_counter_status(
      net => net,
      value => got_reg,
      base_address => base_address,
      bus_handle => bus_handle
    );
    got := got_reg.enabled;

    check_equal(got=>got, expected=>expected, msg=>get_message);
  end procedure;

  -- Check that the current value of the 'pulse_count' field in the 'status' register
  -- equals the given 'expected' value.
  procedure check_counter_status_pulse_count_equal(
    signal net : inout network_t;
    expected : in counter_status_pulse_count_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    message : in string := ""
  ) is
    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Checking the 'pulse_count' field in the 'status' register"
      & register_array_message
      & base_address_message
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;

    variable got_reg : counter_status_t := counter_status_init;
    variable got : counter_status_pulse_count_t := counter_status_pulse_count_init;
  begin
    read_counter_status(
      net => net,
      value => got_reg,
      base_address => base_address,
      bus_handle => bus_handle
    );
    got := got_reg.pulse_count;

    check_equal(got=>got, expected=>expected, msg=>get_message);
  end procedure;
  -- ---------------------------------------------------------------------------

end package body;
