-- -----------------------------------------------------------------------------
-- This file is automatically generated by hdl-registers version 8.1.0.
-- Code generator VhdlSimulationWaitUntilPackageGenerator version 1.0.2.
-- Generated 2026-05-13 20:23 from file regs_counter.toml at Git commit 2feecffd6075 (local changes present).
-- Register hash 71076fb400da5d61dbc4d4b8e12bf513b5d3decf.
-- -----------------------------------------------------------------------------

library ieee;
use ieee.fixed_pkg.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library vunit_lib;
use vunit_lib.bus_master_pkg.bus_master_t;
use vunit_lib.bus_master_pkg.wait_until_read_equals;
use vunit_lib.com_types_pkg.max_timeout;
use vunit_lib.com_types_pkg.network_t;
use vunit_lib.string_ops.hex_image;

library register_file;
use register_file.register_file_pkg.register_t;
use register_file.register_operations_pkg.register_bus_master;

use work.counter_regs_pkg.all;
use work.counter_register_record_pkg.all;


package counter_register_wait_until_pkg is

  -- ---------------------------------------------------------------------------
  -- Wait until the 'conf' register equals the given 'value'.
  procedure wait_until_counter_conf_equals(
    signal net : inout network_t;
    value : in counter_conf_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  );

  -- Wait until the 'condition' field in the 'conf' register equals the given 'value'.
  procedure wait_until_counter_conf_condition_equals(
    signal net : inout network_t;
    value : in counter_conf_condition_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  );

  -- Wait until the 'increment' field in the 'conf' register equals the given 'value'.
  procedure wait_until_counter_conf_increment_equals(
    signal net : inout network_t;
    value : in counter_conf_increment_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  );
  -- ---------------------------------------------------------------------------

  -- ---------------------------------------------------------------------------
  -- Wait until the 'status' register equals the given 'value'.
  procedure wait_until_counter_status_equals(
    signal net : inout network_t;
    value : in counter_status_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  );

  -- Wait until the 'enabled' field in the 'status' register equals the given 'value'.
  procedure wait_until_counter_status_enabled_equals(
    signal net : inout network_t;
    value : in std_ulogic;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  );

  -- Wait until the 'pulse_count' field in the 'status' register equals the given 'value'.
  procedure wait_until_counter_status_pulse_count_equals(
    signal net : inout network_t;
    value : in counter_status_pulse_count_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  );
  -- ---------------------------------------------------------------------------

end package;

package body counter_register_wait_until_pkg is

  -- ---------------------------------------------------------------------------
  -- Wait until the 'conf' register equals the given 'value'.
  procedure wait_until_counter_conf_equals(
    signal net : inout network_t;
    value : in counter_conf_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  ) is
    constant reg_value : register_t := to_slv(value);

    constant reg_index : counter_register_range := counter_conf;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);

    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Timeout while waiting for the 'conf' register"
      & register_array_message
      & base_address_message
      & " to equal the given value: "
      & to_string(reg_value)
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;
  begin
    wait_until_read_equals(
      net => net,
      bus_handle => bus_handle,
      addr => std_ulogic_vector(reg_address),
      value => reg_value,
      timeout => timeout,
      msg => get_message
    );
  end procedure;

  -- Wait until the 'condition' field in the 'conf' register equals the given 'value'.
  procedure wait_until_counter_conf_condition_equals(
    signal net : inout network_t;
    value : in counter_conf_condition_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  ) is
    constant reg_value : register_t := (
      counter_conf_condition => to_slv(value),
      others => '-'
    );

    constant reg_index : counter_register_range := counter_conf;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);

    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Timeout while waiting for the 'condition' field in the 'conf' register"
      & register_array_message
      & base_address_message
      & " to equal the given value: "
      & to_string(reg_value)
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;
  begin
    wait_until_read_equals(
      net => net,
      bus_handle => bus_handle,
      addr => std_ulogic_vector(reg_address),
      value => reg_value,
      timeout => timeout,
      msg => get_message
    );
  end procedure;

  -- Wait until the 'increment' field in the 'conf' register equals the given 'value'.
  procedure wait_until_counter_conf_increment_equals(
    signal net : inout network_t;
    value : in counter_conf_increment_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  ) is
    constant reg_value : register_t := (
      counter_conf_increment => to_counter_conf_increment_slv(value),
      others => '-'
    );

    constant reg_index : counter_register_range := counter_conf;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);

    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Timeout while waiting for the 'increment' field in the 'conf' register"
      & register_array_message
      & base_address_message
      & " to equal the given value: "
      & to_string(reg_value)
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;
  begin
    wait_until_read_equals(
      net => net,
      bus_handle => bus_handle,
      addr => std_ulogic_vector(reg_address),
      value => reg_value,
      timeout => timeout,
      msg => get_message
    );
  end procedure;
  -- ---------------------------------------------------------------------------

  -- ---------------------------------------------------------------------------
  -- Wait until the 'status' register equals the given 'value'.
  procedure wait_until_counter_status_equals(
    signal net : inout network_t;
    value : in counter_status_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  ) is
    constant reg_value : register_t := to_slv(value);

    constant reg_index : counter_register_range := counter_status;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);

    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Timeout while waiting for the 'status' register"
      & register_array_message
      & base_address_message
      & " to equal the given value: "
      & to_string(reg_value)
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;
  begin
    wait_until_read_equals(
      net => net,
      bus_handle => bus_handle,
      addr => std_ulogic_vector(reg_address),
      value => reg_value,
      timeout => timeout,
      msg => get_message
    );
  end procedure;

  -- Wait until the 'enabled' field in the 'status' register equals the given 'value'.
  procedure wait_until_counter_status_enabled_equals(
    signal net : inout network_t;
    value : in std_ulogic;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  ) is
    constant reg_value : register_t := (
      counter_status_enabled => value,
      others => '-'
    );

    constant reg_index : counter_register_range := counter_status;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);

    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Timeout while waiting for the 'enabled' field in the 'status' register"
      & register_array_message
      & base_address_message
      & " to equal the given value: "
      & to_string(reg_value)
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;
  begin
    wait_until_read_equals(
      net => net,
      bus_handle => bus_handle,
      addr => std_ulogic_vector(reg_address),
      value => reg_value,
      timeout => timeout,
      msg => get_message
    );
  end procedure;

  -- Wait until the 'pulse_count' field in the 'status' register equals the given 'value'.
  procedure wait_until_counter_status_pulse_count_equals(
    signal net : inout network_t;
    value : in counter_status_pulse_count_t;
    base_address : in unsigned(32 - 1 downto 0) := (others => '0');
    bus_handle : in bus_master_t := register_bus_master;
    timeout : delay_length := max_timeout;
    message : string := ""
  ) is
    constant reg_value : register_t := (
      counter_status_pulse_count => to_counter_status_pulse_count_slv(value),
      others => '-'
    );

    constant reg_index : counter_register_range := counter_status;
    constant reg_address : unsigned(32 - 1 downto 0) := base_address + to_unsigned(4 * reg_index, 32);

    constant register_array_message : string := "";
    function base_address_message return string is
    begin
      if base_address /= 0 then
        return " (at base address " & hex_image(std_logic_vector(base_address)) & ")";
      end if;

      return "";
    end function;
    constant base_message : string := (
      "Timeout while waiting for the 'pulse_count' field in the 'status' register"
      & register_array_message
      & base_address_message
      & " to equal the given value: "
      & to_string(reg_value)
      & "."
    );
    function get_message return string is
    begin
      if message = "" then
        return base_message;
      end if;

      return base_message & " " & message & ".";
    end function;
  begin
    wait_until_read_equals(
      net => net,
      bus_handle => bus_handle,
      addr => std_ulogic_vector(reg_address),
      value => reg_value,
      timeout => timeout,
      msg => get_message
    );
  end procedure;
  -- ---------------------------------------------------------------------------

end package body;
