-- -----------------------------------------------------------------------------
-- This file is automatically generated by hdl-registers version 8.1.0.
-- Code generator VhdlRegisterPackageGenerator version 2.0.0.
-- Generated 2026-05-10 00:13 from file toml-example.toml.
-- Register hash 8f44eade873eb5c83fa923c770ff571544a8f633.
-- -----------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

library register_file;
use register_file.register_file_pkg.all;


package caesar_regs_pkg is

  -- ---------------------------------------------------------------------------
  -- Values of register constants.
  constant caesar_constant_axi_data_width : integer := 64;
  constant caesar_constant_clock_rate_hz : real := 156250000.0;

  -- ---------------------------------------------------------------------------
  -- The valid range of register indexes.
  subtype caesar_register_range is natural range 0 to 9;

  -- ---------------------------------------------------------------------------
  -- The number of bits needed to address all 10 registers on a register bus.
  -- Note that this figure includes the lowest two address bits that are assumed zero, since
  -- registers are 32-bit and unaligned accesses are not supported.
  constant caesar_address_width : positive := 6;

  -- Number of times the 'channels' register array is repeated.
  constant caesar_channels_array_length : natural := 4;
  -- Range for indexing 'channels' register array repetitions.
  subtype caesar_channels_range is natural range 0 to 3;

  -- Register indexes, within the list of registers.
  constant caesar_conf : natural := 0;
  constant caesar_status : natural := 1;
  function caesar_channels_read_address(
    array_index : caesar_channels_range
  ) return caesar_register_range;
  function caesar_channels_conf(
    array_index : caesar_channels_range
  ) return caesar_register_range;

  -- Declare 'register_map' and 'regs_init' constants here but define them in
  -- the package body (deferred constants).
  -- So that functions have been elaborated when they are called.
  -- Needed for ModelSim compilation to pass.

  -- To be used as the 'registers' generic of 'axi_lite_register_file.vhd'.
  constant caesar_register_map : register_definition_vec_t(caesar_register_range);

  -- To be used for the 'regs_up' and 'regs_down' ports of 'axi_lite_register_file.vhd'.
  subtype caesar_regs_t is register_vec_t(caesar_register_range);
  -- To be used as the 'default_values' generic of 'axi_lite_register_file.vhd'.
  constant caesar_regs_init : caesar_regs_t;

  -- To be used for the 'reg_was_read' and 'reg_was_written' ports of 'axi_lite_register_file.vhd'.
  subtype caesar_reg_was_accessed_t is std_ulogic_vector(caesar_register_range);

  -- -----------------------------------------------------------------------------
  -- Fields in the 'conf' register.
  -- Range of the 'enable' field.
  constant caesar_conf_enable : natural := 0;
  -- Default value of the 'enable' field.
  constant caesar_conf_enable_init : std_ulogic := '1';

  -- Range of the 'direction' field.
  subtype caesar_conf_direction is natural range 2 downto 1;
  -- Width of the 'direction' field.
  constant caesar_conf_direction_width : positive := 2;
  -- Type for the 'direction' field.
  type caesar_conf_direction_t is (
    direction_data_in,
    direction_high_z,
    direction_data_out
  );
  -- Default value of the 'direction' field.
  constant caesar_conf_direction_init : caesar_conf_direction_t := direction_high_z;
  -- Type for the 'direction' field as an SLV.
  subtype caesar_conf_direction_slv_t is std_ulogic_vector(1 downto 0);
  -- Cast a 'direction' field value to SLV.
  function to_slv(data : caesar_conf_direction_t) return caesar_conf_direction_slv_t;
  -- Get a 'direction' field value from a register value.
  function to_caesar_conf_direction(data : register_t) return caesar_conf_direction_t;

  -- -----------------------------------------------------------------------------
  -- Fields in the 'conf' register within the 'channels' register array.
  -- Range of the 'enable' field.
  constant caesar_channels_conf_enable : natural := 0;
  -- Default value of the 'enable' field.
  constant caesar_channels_conf_enable_init : std_ulogic := '0';

  -- Range of the 'tuser' field.
  subtype caesar_channels_conf_tuser is natural range 8 downto 1;
  -- Width of the 'tuser' field.
  constant caesar_channels_conf_tuser_width : positive := 8;
  -- Type for the 'tuser' field.
  subtype caesar_channels_conf_tuser_t is u_unsigned(7 downto 0);
  -- Default value of the 'tuser' field.
  constant caesar_channels_conf_tuser_init : caesar_channels_conf_tuser_t := "00000000";

end package;

package body caesar_regs_pkg is

  function caesar_channels_read_address(
    array_index : caesar_channels_range
  ) return caesar_register_range is
  begin
    return 2 + array_index * 2 + 0;
  end function;

  function caesar_channels_conf(
    array_index : caesar_channels_range
  ) return caesar_register_range is
  begin
    return 2 + array_index * 2 + 1;
  end function;

  constant caesar_register_map : register_definition_vec_t(caesar_register_range) := (
    0 => (index => caesar_conf, mode => r_w, utilized_width => 3),
    1 => (index => caesar_status, mode => r, utilized_width => 32),
    2 => (index => caesar_channels_read_address(0), mode => r_w, utilized_width => 32),
    3 => (index => caesar_channels_conf(0), mode => w, utilized_width => 9),
    4 => (index => caesar_channels_read_address(1), mode => r_w, utilized_width => 32),
    5 => (index => caesar_channels_conf(1), mode => w, utilized_width => 9),
    6 => (index => caesar_channels_read_address(2), mode => r_w, utilized_width => 32),
    7 => (index => caesar_channels_conf(2), mode => w, utilized_width => 9),
    8 => (index => caesar_channels_read_address(3), mode => r_w, utilized_width => 32),
    9 => (index => caesar_channels_conf(3), mode => w, utilized_width => 9)
  );

  constant caesar_regs_init : caesar_regs_t := (
    0 => "00000000000000000000000000000011",
    1 => "00000000000000000000000000000000",
    2 => "00000000000000000000000000000000",
    3 => "00000000000000000000000000000000",
    4 => "00000000000000000000000000000000",
    5 => "00000000000000000000000000000000",
    6 => "00000000000000000000000000000000",
    7 => "00000000000000000000000000000000",
    8 => "00000000000000000000000000000000",
    9 => "00000000000000000000000000000000"
  );

  -- Cast a 'direction' field value to SLV.
  function to_slv(data : caesar_conf_direction_t) return caesar_conf_direction_slv_t is
    constant data_int : natural := caesar_conf_direction_t'pos(data);
    constant result : caesar_conf_direction_slv_t := std_ulogic_vector(
      to_unsigned(data_int, caesar_conf_direction_width)
    );
  begin
    return result;
  end function;

  -- Get a 'direction' field value from a register value.
  function to_caesar_conf_direction(data : register_t) return caesar_conf_direction_t is
    constant field_slv : caesar_conf_direction_slv_t := data(caesar_conf_direction);
    constant field_int : natural := to_integer(unsigned(field_slv));
    constant result : caesar_conf_direction_t := caesar_conf_direction_t'val(field_int);
  begin
    return result;
  end function;

end package body;
